# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 511)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.TitlePart1 = QtWidgets.QLabel(self.centralwidget)
        self.TitlePart1.setStyleSheet("font: 16pt \"Sans Serif\";\n"
"")
        self.TitlePart1.setObjectName("TitlePart1")
        self.gridLayout.addWidget(self.TitlePart1, 0, 0, 1, 2)
        self.monAft = QtWidgets.QCheckBox(self.centralwidget)
        self.monAft.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.monAft.setObjectName("monAft")
        self.gridLayout.addWidget(self.monAft, 3, 0, 1, 1)
        self.tueAft = QtWidgets.QCheckBox(self.centralwidget)
        self.tueAft.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.tueAft.setObjectName("tueAft")
        self.gridLayout.addWidget(self.tueAft, 3, 1, 1, 1)
        self.monEve = QtWidgets.QCheckBox(self.centralwidget)
        self.monEve.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.monEve.setObjectName("monEve")
        self.gridLayout.addWidget(self.monEve, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(0, 0, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.tueEve = QtWidgets.QCheckBox(self.centralwidget)
        self.tueEve.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.tueEve.setObjectName("tueEve")
        self.gridLayout.addWidget(self.tueEve, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(0, 0, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.tueMor = QtWidgets.QCheckBox(self.centralwidget)
        self.tueMor.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.tueMor.setObjectName("tueMor")
        self.gridLayout.addWidget(self.tueMor, 2, 1, 1, 1)
        self.monMor = QtWidgets.QCheckBox(self.centralwidget)
        self.monMor.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.monMor.setObjectName("monMor")
        self.gridLayout.addWidget(self.monMor, 2, 0, 1, 1)
        self.wedMor = QtWidgets.QCheckBox(self.centralwidget)
        self.wedMor.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.wedMor.setObjectName("wedMor")
        self.gridLayout.addWidget(self.wedMor, 6, 0, 1, 1)
        self.thuMor = QtWidgets.QCheckBox(self.centralwidget)
        self.thuMor.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.thuMor.setObjectName("thuMor")
        self.gridLayout.addWidget(self.thuMor, 6, 1, 1, 1)
        self.wedAft = QtWidgets.QCheckBox(self.centralwidget)
        self.wedAft.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.wedAft.setObjectName("wedAft")
        self.gridLayout.addWidget(self.wedAft, 7, 0, 1, 1)
        self.thuAft = QtWidgets.QCheckBox(self.centralwidget)
        self.thuAft.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.thuAft.setObjectName("thuAft")
        self.gridLayout.addWidget(self.thuAft, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(0, 0, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.wedEve = QtWidgets.QCheckBox(self.centralwidget)
        self.wedEve.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.wedEve.setObjectName("wedEve")
        self.gridLayout.addWidget(self.wedEve, 8, 0, 1, 1)
        self.thuEve = QtWidgets.QCheckBox(self.centralwidget)
        self.thuEve.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.thuEve.setObjectName("thuEve")
        self.gridLayout.addWidget(self.thuEve, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(0, 0, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(0, 0, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 1, 1, 1)
        self.friMor = QtWidgets.QCheckBox(self.centralwidget)
        self.friMor.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.friMor.setObjectName("friMor")
        self.gridLayout.addWidget(self.friMor, 10, 0, 1, 1)
        self.satMor = QtWidgets.QCheckBox(self.centralwidget)
        self.satMor.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.satMor.setObjectName("satMor")
        self.gridLayout.addWidget(self.satMor, 10, 1, 1, 1)
        self.friAft = QtWidgets.QCheckBox(self.centralwidget)
        self.friAft.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.friAft.setObjectName("friAft")
        self.gridLayout.addWidget(self.friAft, 11, 0, 1, 1)
        self.satAft = QtWidgets.QCheckBox(self.centralwidget)
        self.satAft.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.satAft.setObjectName("satAft")
        self.gridLayout.addWidget(self.satAft, 11, 1, 1, 1)
        self.friEve = QtWidgets.QCheckBox(self.centralwidget)
        self.friEve.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.friEve.setObjectName("friEve")
        self.gridLayout.addWidget(self.friEve, 12, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(0, 0, 255);")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 13, 0, 1, 1)
        self.sunMor = QtWidgets.QCheckBox(self.centralwidget)
        self.sunMor.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.sunMor.setObjectName("sunMor")
        self.gridLayout.addWidget(self.sunMor, 14, 0, 1, 1)
        self.sunAft = QtWidgets.QCheckBox(self.centralwidget)
        self.sunAft.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.sunAft.setObjectName("sunAft")
        self.gridLayout.addWidget(self.sunAft, 15, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(0, 0, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setObjectName("btnBack")
        self.gridLayout.addWidget(self.btnBack, 14, 1, 1, 1)
        self.btnNext = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext.setObjectName("btnNext")
        self.gridLayout.addWidget(self.btnNext, 15, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Helpdesk Scheduler v1.0"))
        self.TitlePart1.setText(_translate("MainWindow", "Part 1: Select the shifts that you CAN work"))
        self.monAft.setText(_translate("MainWindow", "1:00pm - 5:00pm"))
        self.tueAft.setText(_translate("MainWindow", "1:00pm - 5:00pm"))
        self.monEve.setText(_translate("MainWindow", "5:00pm - 9:00pm"))
        self.label.setText(_translate("MainWindow", "Monday"))
        self.tueEve.setText(_translate("MainWindow", "5:00pm - 9:00pm"))
        self.label_4.setText(_translate("MainWindow", "Thursday"))
        self.tueMor.setText(_translate("MainWindow", "9:00am - 1:00pm"))
        self.monMor.setText(_translate("MainWindow", "9:00am - 1:00pm"))
        self.wedMor.setText(_translate("MainWindow", "9:00am - 1:00pm"))
        self.thuMor.setText(_translate("MainWindow", "9:00am - 1:00pm"))
        self.wedAft.setText(_translate("MainWindow", "1:00pm - 5:00pm"))
        self.thuAft.setText(_translate("MainWindow", "1:00pm - 5:00pm"))
        self.label_2.setText(_translate("MainWindow", "Tuesday"))
        self.wedEve.setText(_translate("MainWindow", "5:00pm - 9:00pm"))
        self.thuEve.setText(_translate("MainWindow", "5:00pm - 9:00pm"))
        self.label_5.setText(_translate("MainWindow", "Friday"))
        self.label_6.setText(_translate("MainWindow", "Saturday"))
        self.friMor.setText(_translate("MainWindow", "9:00am - 1:00pm"))
        self.satMor.setText(_translate("MainWindow", "9:00am - 1:00pm"))
        self.friAft.setText(_translate("MainWindow", "1:00pm - 5:00pm"))
        self.satAft.setText(_translate("MainWindow", "1:00pm - 5:00pm"))
        self.friEve.setText(_translate("MainWindow", "5:00pm - 9:00pm"))
        self.label_7.setText(_translate("MainWindow", "Sunday"))
        self.sunMor.setText(_translate("MainWindow", "9:00am - 1:00pm"))
        self.sunAft.setText(_translate("MainWindow", "1:00pm - 5:00pm"))
        self.label_3.setText(_translate("MainWindow", "Wednesday"))
        self.btnBack.setText(_translate("MainWindow", "Back"))
        self.btnNext.setText(_translate("MainWindow", "Next"))

